documentation:
  - changed-files: 
    - any-glob-to-any-file: '*.md'

build:
  - changed-files:
    - any-glob-to-any-file: 'pyproject.toml'
    - any-glob-to-any-file: .github/*

commands:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*command.py'
    - any-glob-to-any-file: 'src/**/*command*.py'