[project]
name = "blackwall-protocol"
version = "0.0.0"
requires-python = ">= 3.13"
dependencies = [
  "racfu",
  "textual"
]
authors = [
  {name = "Emma Skovgaard"}
]
readme = "README.md"
keywords = ["RACF", "security", "mainframe"]

[project.urls]
Repository = "https://github.com/EmmasBox/blackwall-protocol.git"
Issues = "https://github.com/EmmasBox/blackwall-protocol/issues"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
