[project]
name = "blackwall-protocol"
version = "0.1.0"
requires-python = ">= 3.11"
dependencies = [
  "racfu",
  "textual>2.1"
]
authors = [
  {name = "Emma Skovgaard"}
]
readme = "README.md"
keywords = ["RACF", "security", "mainframe"]

[project.scripts]
blackwall = "blackwall.main:main"

[project.urls]
Repository = "https://github.com/EmmasBox/blackwall-protocol.git"
Issues = "https://github.com/EmmasBox/blackwall-protocol/issues"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
