[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "blackwall-protocol"
requires-python = ">= 3.13"
dependencies = [
  "racfu",
  "textual"
]
authors = [
  {name = "Emma Skovgaard"}
]
readme = "README.md"
keywords = ["RACF", "security", "mainframe"]