[build-system]

[project]
name = "blackwall-protocol"
requires-python = ">= 3.13"
dependencies = [
  "racfu",
  "textual"
]
authors = [
  {name = "Emma Skovgaard"}
]
readme = {file = "README.md", content-type = "text/markdown"}
keywords = ["RACF", "security", "mainframe"]